In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from datetime import datetime, timedelta
import pandas as pd
import DB_connection

In [2]:
driver = webdriver.Chrome('./chromedriver')

In [3]:
driver.get("http://oasis.krei.re.kr/basicInfo/etc/kma.do")

In [4]:
driver.implicitly_wait(3)

In [5]:
driver.find_element_by_id('sCalendar').click()
driver.find_element_by_id('sCalendar').clear()

In [6]:
yesterday = datetime.now() - timedelta(days=1)
yesterday = yesterday.strftime('%Y-%m-%d')

driver.find_element_by_id('sCalendar').send_keys(yesterday)

In [7]:
driver.implicitly_wait(3)

In [8]:
driver.find_element_by_id('search2').click()

In [9]:
select = Select(driver.find_element_by_id('pageUnit'))
select.select_by_value('500')

In [10]:
results_table = []
rows = driver.find_elements_by_css_selector(".data_table tbody tr")

for row in rows:

    temp = []
    columns = row.find_elements_by_css_selector("td")

    for column in columns:

        temp.append(column.text)

    results_table.append(temp)

In [11]:
data = pd.DataFrame(results_table)

In [12]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,2020-06-07,서울,종로구,22.7,29.2,19.2,0.0,9.0,26.0,69.0,3.0,0.0,7.3
1,2020-06-07,강원도,춘천시,24.8,30.1,19.9,0.0,12.0,26.0,64.0,0.0,0.0,4.8
2,2020-06-07,강원도,철원군,22.3,28.0,17.6,0.0,10.0,23.0,84.0,4.0,0.0,6.5
3,2020-06-07,강원도,속초시,19.7,23.4,16.7,0.0,13.0,0.0,78.0,2.0,0.0,6.1
4,2020-06-07,강원도,원주시,23.9,29.0,20.2,0.0,10.0,27.0,50.0,3.0,0.0,5.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,2020-06-07,경상북도,울진군,18.4,21.3,13.9,0.0,11.0,0.0,73.0,3.0,0.0,5.2
67,2020-06-07,경상북도,의성군,22.2,31.6,11.5,0.0,11.0,0.0,54.0,2.0,0.0,5.0
68,2020-06-07,경상북도,영천시,21.2,29.9,12.2,0.0,12.0,0.0,58.0,1.0,0.0,6.5
69,2020-06-07,경상북도,포항시,21.1,26.3,16.0,0.0,13.0,27.0,63.0,1.0,0.0,6.9
70,2020-06-07,경상북도,울릉군,19.4,22.9,14.6,0.0,13.0,31.0,59.0,0.0,0.0,5.8

In [13]:
#1,4,5,8,9,10,11,12
del data[1], data[4], data[5], data[8], data[9], data[10], data[11], data[12]

In [14]:
#고창군, 안동시, 고흥군, 의성군, 신안군
data = data[data[2].isin(["고창군", "안동시", "고흥군", "의성군", "신안군"])]

In [15]:
data

             0    2     3    6     7
31  2020-06-07  신안군  18.6  0.0  11.0
33  2020-06-07  고흥군  20.7  0.0  12.0
41  2020-06-07  고창군  22.2  0.0   8.0
64  2020-06-07  안동시  22.5  0.0  12.0
67  2020-06-07  의성군  22.2  0.0  11.0

In [16]:
data.loc[data[2] == "고창군", 2] = "Gochang"
data.loc[data[2] == "고흥군", 2] = "Goheung"
data.loc[data[2] == "신안군", 2] = "Sinan"
data.loc[data[2] == "안동시", 2] = "Andong"
data.loc[data[2] == "의성군", 2] = "Uiseong"

/Users/kimsejin/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
/Users/kimsejin/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/kimsejin/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/kimsejin/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/kimsejin/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/kimsejin/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [17]:
data

             0        2     3    6     7
31  2020-06-07    Sinan  18.6  0.0  11.0
33  2020-06-07  Goheung  20.7  0.0  12.0
41  2020-06-07  Gochang  22.2  0.0   8.0
64  2020-06-07   Andong  22.5  0.0  12.0
67  2020-06-07  Uiseong  22.2  0.0  11.0

In [18]:
data.columns=["days", "region", "temperature", "rainfall", "daylight"]

In [19]:
yesterday = datetime.now() - timedelta(days=1)
weeks = yesterday.isocalendar()[1]

In [20]:
data['weeks'] = weeks

/Users/kimsejin/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [21]:
data.sort_values(by=['region'], axis=0,inplace=True)
data.reset_index(drop=True, inplace=True)
data

/Users/kimsejin/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

         days   region temperature rainfall daylight  weeks
0  2020-06-07   Andong        22.5      0.0     12.0     23
1  2020-06-07  Gochang        22.2      0.0      8.0     23
2  2020-06-07  Goheung        20.7      0.0     12.0     23
3  2020-06-07    Sinan        18.6      0.0     11.0     23
4  2020-06-07  Uiseong        22.2      0.0     11.0     23

In [22]:
data['temperature'] = pd.to_numeric(data['temperature'])
data['rainfall'] = pd.to_numeric(data['rainfall'])
data['daylight'] = pd.to_numeric(data['daylight'])
del data['days'], data['weeks']

/Users/kimsejin/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/kimsejin/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/kimsejin/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
conn = DB_connection.engine.connect()

In [24]:
weatherData = pd.read_sql_table('weather', conn)

In [25]:
weatherData.head()

        days   region  temperature  rainfall  daylight  weeks
0 2015-01-01    Sinan          0.0       1.5       3.0      1
1 2015-01-01  Goheung         -1.5       0.0       6.0      1
2 2015-01-01  Gochang         -4.1       8.5       1.0      1
3 2015-01-01   Andong         -6.7       0.0       9.0      1
4 2015-01-01  Uiseong         -7.2       0.0       8.0      1

In [26]:
average = weatherData.groupby([weatherData["region"], weatherData["weeks"]], as_index=False).mean()
pd.set_option('display.max_rows', 300)
average

      region  weeks  temperature   rainfall   daylight
0     Andong      1    -0.495833   0.000000   6.666667
1     Andong      2    -0.831707   1.380488   7.097561
2     Andong      3    -0.930952   0.280952   7.119048
3     Andong      4    -2.154762   0.292857   7.380952
4     Andong      5    -0.483333   0.354762   6.738095
5     Andong      6    -1.488095   0.280952   8.476190
6     Andong      7     1.461905   1.076190   8.047619
7     Andong      8     1.753659   1.551220   7.146341
8     Andong      9     3.895122   1.434146   7.390244
9     Andong     10     4.160976   2.407317   7.707317
10    Andong     11     5.924390   0.700000   8.073171
11    Andong     12     7.819512   2.619512   7.536585
12    Andong     13     9.304762   0.478571   8.690476
13    Andong     14    11.123810   2.373810   8.166667
14    Andong     15    11.235714   3.290476   8.071429
15    Andong     16    12.930952   2.047619   8.428571
16    Andong     17    13.852381   3.788095   7.714286
17    Andong     18    17.451282   1.228205  10.179487
18    Andong     19    16.935714   2.397619   8.000000
19    Andong     20    18.800000   2.333333   8.690476
20    Andong     21    18.330000   1.555000   9.925000
21    Andong     22    21.205714   1.094286  10.314286
22    Andong     23    21.302857   1.534286   9.600000
23    Andong     24    20.854286   0.408571   8.000000
24    Andong     25    23.454286   1.645714   8.800000
25    Andong     26    23.602857   6.662857   6.771429
26    Andong     27    23.720000  11.171429   6.914286
27    Andong     28    24.277143   8.157143   6.428571
28    Andong     29    26.031429   3.582857   7.285714
29    Andong     30    25.880000   6.054286   6.914286
30    Andong     31    28.202857   3.320000   9.485714
31    Andong     32    27.677143   4.391429   8.971429
32    Andong     33    26.622857   2.211429   7.542857
33    Andong     34    26.102857   2.957143   7.828571
34    Andong     35    22.360000   7.860000   6.742857
35    Andong     36    21.902857   5.714286   5.314286
36    Andong     37    20.014286   1.620000   4.885714
37    Andong     38    20.014286   4.525714   6.685714
38    Andong     39    18.505714   3.294286   6.000000
39    Andong     40    18.571429   8.451429   5.085714
40    Andong     41    16.042857   2.614286   7.171429
41    Andong     42    13.580000   0.131429   6.657143
42    Andong     43    13.900000   0.385714   5.914286
43    Andong     44    10.347059   1.402941   7.323529
44    Andong     45     9.721429   1.596429   6.714286
45    Andong     46     7.717857   1.864286   5.107143
46    Andong     47     5.303571   1.742857   5.321429
47    Andong     48     4.346429   0.378571   4.892857
48    Andong     49     2.003125   0.925000   6.125000
49    Andong     50     0.017647   0.570588   6.147059
50    Andong     51     0.815625   0.237500   6.468750
51    Andong     52     0.662500   1.171875   4.218750
52    Andong     53    -0.631250   1.587500   6.750000
53   Gochang      1    -2.854167   0.604167   3.375000
54   Gochang      2     1.336585   1.943902   4.170732
55   Gochang      3     0.847619   0.714286   4.952381
56   Gochang      4    -0.707143   1.064286   5.000000
57   Gochang      5     0.457143   1.557143   4.333333
58   Gochang      6    -0.619048   0.550000   5.095238
59   Gochang      7     2.790476   0.845238   6.071429
60   Gochang      8     2.912195   1.929268   5.073171
61   Gochang      9     4.309756   1.624390   6.097561
62   Gochang     10     5.070732   1.031707   6.024390
63   Gochang     11     6.121951   1.082927   6.853659
64   Gochang     12     8.051220   2.307317   6.268293
65   Gochang     13     8.652381   1.030952   8.119048
66   Gochang     14    10.959524   2.335714   7.285714
67   Gochang     15    10.880952   3.635714   6.357143
68   Gochang     16    12.745238   2.276190   6.809524
69   Gochang     17    13.695238   2.590476   6.357143
70   Gochang     18    16.505128   3.923077   7.564103
71   Gochang     19    16.480952   3.919048   6.833333
72   Gochang     20    18.264286   2.352381   7.285714
73   Gochang     21    17.922500   1.862500   8.600000
74   Gochang     22    19.817143   2.020000   8.371429
75   Gochang     23    20.434286   1.205714   7.057143
76   Gochang     24    21.371429   0.057143   6.714286
77   Gochang     25    22.148571   1.325714   6.228571
78   Gochang     26    23.262857  10.048571   4.028571
79   Gochang     27    24.014286   7.042857   4.285714
80   Gochang     28    24.860000   8.000000   4.571429
81   Gochang     29    25.802857   8.974286   5.628571
82   Gochang     30    26.582857   2.868571   5.685714
83   Gochang     31    24.738235   1.226471   7.441176
84   Gochang     32    28.165714   1.828571   7.657143
85   Gochang     33    26.974286   4.274286   6.342857
86   Gochang     34    26.245714  15.694286   5.285714
87   Gochang     35    23.354286   5.600000   5.600000
88   Gochang     36    22.965714   6.062857   4.942857
89   Gochang     37    21.085714   2.848571   5.057143
90   Gochang     38    20.940000   6.025714   5.742857
91   Gochang     39    19.622857   4.185714   6.342857
92   Gochang     40    19.165714  10.322857   4.628571
93   Gochang     41    16.754286   3.585714   6.457143
94   Gochang     42    14.194286   0.260000   6.800000
95   Gochang     43    14.954286   1.474286   6.057143
96   Gochang     44    11.902941   1.117647   6.705882
97   Gochang     45     2.982143   1.803571   5.607143
98   Gochang     46     9.200000   1.625000   4.750000
99   Gochang     47     7.903571   1.735714   4.000000
100  Gochang     48     5.700000   1.257143   4.392857
101  Gochang     49     4.003125   2.387500   3.843750
102  Gochang     50     2.741176   0.911765   4.794118
103  Gochang     51     3.212500   0.959375   3.375000
104  Gochang     52     3.318750   1.831250   2.906250
105  Gochang     53     1.543750   1.425000   4.562500
106  Goheung      1     2.525000   0.066667   5.333333
107  Goheung      2     2.765854   1.714634   5.439024
108  Goheung      3     1.847619   0.564286   6.071429
109  Goheung      4     1.147619   0.538095   6.119048
110  Goheung      5     1.921429   2.578571   4.690476
111  Goheung      6     1.026190   0.271429   6.761905
112  Goheung      7     3.576190   1.885714   6.619048
113  Goheung      8     3.914634   2.690244   5.634146
114  Goheung      9     5.485366   1.429268   6.512195
115  Goheung     10     5.824390   2.780488   6.439024
116  Goheung     11     6.748780   4.019512   7.390244
117  Goheung     12     8.717073   4.348780   6.268293
118  Goheung     13     9.673810   0.838095   7.880952
119  Goheung     14    11.507143   4.333333   7.309524
120  Goheung     15    11.821429   4.023810   6.095238
121  Goheung     16    12.588095   4.223810   7.166667
122  Goheung     17    13.933333   3.740476   6.666667
123  Goheung     18    15.779487   6.271795   7.512821
124  Goheung     19    16.383333   7.059524   6.738095
125  Goheung     20    17.428571   5.830952   7.142857
126  Goheung     21    17.617500   1.560000   8.175000
127  Goheung     22    20.151429   2.157143   7.857143
128  Goheung     23    20.222857   4.342857   7.714286
129  Goheung     24    20.060000   1.171429   5.514286
130  Goheung     25    21.908571   1.131429   6.114286
131  Goheung     26    22.368571  21.542857   3.342857
132  Goheung     27    23.297143  10.594286   3.742857
133  Goheung     28    24.031429   7.251429   4.400000
134  Goheung     29    25.117143  14.008571   6.257143
135  Goheung     30    25.262857   2.008571   5.942857
136  Goheung     31    27.677143   0.117143   8.742857
137  Goheung     32    27.574286   0.431429   8.171429
138  Goheung     33    26.705714   3.828571   6.800000
139  Goheung     34    26.094286   7.505714   6.114286
140  Goheung     35    23.500000   3.165714   5.485714
141  Goheung     36    22.551429  11.005714   3.742857
142  Goheung     37    21.300000   3.414286   5.114286
143  Goheung     38    21.051429   9.220000   5.571429
144  Goheung     39    19.894286   3.200000   5.914286
145  Goheung     40    19.868571  20.417143   4.114286
146  Goheung     41    17.377143   4.885714   6.485714
147  Goheung     42    15.228571   0.074286   6.342857
148  Goheung     43    15.365714   0.585714   5.971429
149  Goheung     44    12.250000   0.629412   7.176471
150  Goheung     45    11.517857   1.692857   6.250000
151  Goheung     46     9.992857   1.260714   5.357143
152  Goheung     47     8.350000   1.350000   4.714286
153  Goheung     48     7.167857   0.467857   5.250000
154  Goheung     49     4.803125   1.468750   4.875000
155  Goheung     50     3.623529   0.485294   5.617647
156  Goheung     51     4.078125   0.193750   5.406250
157  Goheung     52     4.187500   3.184375   4.000000
158  Goheung     53     2.325000   1.793750   6.000000
159    Sinan      1     5.258333   0.220833   3.500000
160    Sinan      2     4.497561   1.217073   3.097561
161    Sinan      3     4.280952   0.619048   4.238095
162    Sinan      4     2.907143   0.638095   4.190476
163    Sinan      5     3.280952   1.452381   3.452381
164    Sinan      6     2.564286   0.473810   4.190476
165    Sinan      7     4.671429   1.138095   5.857143
166    Sinan      8     4.531707   1.968293   5.121951
167    Sinan      9     5.634146   1.065854   6.365854
168    Sinan     10     5.739024   1.897561   6.487805
169    Sinan     11     6.507317   0.878049   7.560976
170    Sinan     12     7.819512   2.695122   6.707317
171    Sinan     13     8.009524   0.516667   8.023810
172    Sinan     14     9.471429   2.190476   6.404762
173    Sinan     15     9.569048   4.335714   6.404762
174    Sinan     16    11.159524   1.688095   7.452381
175    Sinan     17    12.159524   3.914286   6.833333
176    Sinan     18    14.266667   4.602564   7.461538
177    Sinan     19    14.200000   6.609524   6.809524
178    Sinan     20    15.571429   2.557143   6.333333
179    Sinan     21    16.202500   1.385000   7.475000
180    Sinan     22    17.645714   2.314286   6.257143
181    Sinan     23    18.122857   3.148571   6.971429
182    Sinan     24    18.651429   0.437143   6.514286
183    Sinan     25    19.811429   1.085714   5.400000
184    Sinan     26    20.660000  15.211429   3.628571
185    Sinan     27    21.371429  10.177143   3.971429
186    Sinan     28    21.854286   4.037143   3.314286
187    Sinan     29    23.105714   5.597143   4.371429
188    Sinan     30    16.551429   2.008571   4.600000
189    Sinan     31    11.474286   0.460000   5.285714
190    Sinan     32    26.271429   0.725714   7.914286
191    Sinan     33    25.525714   6.302857   6.828571
192    Sinan     34    25.185714   8.700000   6.628571
193    Sinan     35    22.962857   4.800000   5.828571
194    Sinan     36    22.428571   8.391429   5.400000
195    Sinan     37    20.565714   4.028571   5.571429
196    Sinan     38    20.965714   7.417143   6.657143
197    Sinan     39    19.994286   1.988571   7.028571
198    Sinan     40    19.337143  12.537143   5.285714
199    Sinan     41    17.854286   2.708571   5.971429
200    Sinan     42    16.285714   0.194286   6.600000
201    Sinan     43    16.328571   1.108571   6.314286
202    Sinan     44    14.452941   1.438235   6.500000
203    Sinan     45    13.785714   2.800000   6.214286
204    Sinan     46    12.139286   2.546429   4.392857
205    Sinan     47    11.064286   1.250000   4.142857
206    Sinan     48     8.767857   0.682143   4.178571
207    Sinan     49     7.309375   2.356250   3.375000
208    Sinan     50     6.538235   1.544118   3.735294
209    Sinan     51     6.612500   0.643750   3.250000
210    Sinan     52     6.221875   2.121875   2.656250
211    Sinan     53     4.675000   1.937500   2.187500
212  Uiseong      1    -2.137500   0.000000   5.250000
213  Uiseong      2    -1.719512   1.292683   5.365854
214  Uiseong      3    -1.969048   0.307143   6.238095
215  Uiseong      4    -2.766667   0.307143   6.500000
216  Uiseong      5    -1.423810   0.630952   5.761905
217  Uiseong      6    -2.352381   0.202381   7.571429
218  Uiseong      7     0.538095   0.680952   7.500000
219  Uiseong      8     1.314634   1.314634   5.926829
220  Uiseong      9     3.251220   1.453659   6.268293
221  Uiseong     10     3.758537   2.580488   6.756098
222  Uiseong     11     5.358537   0.621951   7.365854
223  Uiseong     12     7.170732   2.758537   6.682927
224  Uiseong     13     8.759524   0.626190   7.357143
225  Uiseong     14    10.516667   2.273810   7.119048
226  Uiseong     15    10.807143   3.359524   6.857143
227  Uiseong     16    12.416667   2.066667   7.285714
228  Uiseong     17    13.485714   3.319048   6.880952
229  Uiseong     18    16.446154   1.571795   9.205128
230  Uiseong     19    16.564286   2.085714   7.309524
231  Uiseong     20    18.269048   2.588095   7.976190
232  Uiseong     21    17.677500   1.607500   9.250000
233  Uiseong     22    20.594286   1.080000   9.657143
234  Uiseong     23    20.957143   1.302857   8.828571
235  Uiseong     24    20.771429   0.754286   6.857143
236  Uiseong     25    23.351429   1.320000   7.342857
237  Uiseong     26    23.617143   5.777143   5.228571
238  Uiseong     27    23.854286   9.402857   5.685714
239  Uiseong     28    24.448571   6.071429   5.428571
240  Uiseong     29    26.048571   2.562857   6.285714
241  Uiseong     30    26.034286   5.137143   5.914286
242  Uiseong     31    28.385714   1.897143   8.742857
243  Uiseong     32    28.008571   1.517143   7.628571
244  Uiseong     33    26.748571   4.071429   6.285714
245  Uiseong     34    26.117143   3.737143   5.971429
246  Uiseong     35    22.531429   5.708571   5.514286
247  Uiseong     36    22.011429   7.162857   4.142857
248  Uiseong     37    20.028571   2.637143   4.257143
249  Uiseong     38    19.728571   5.008571   5.714286
250  Uiseong     39    18.151429   3.062857   5.200000
251  Uiseong     40    18.668571   8.031429   4.342857
252  Uiseong     41    15.640000   3.048571   6.428571
253  Uiseong     42    12.820000   0.177143   5.742857
254  Uiseong     43    13.228571   0.528571   5.200000
255  Uiseong     44     9.305882   0.970588   7.205882
256  Uiseong     45     8.878571   1.296429   7.142857
257  Uiseong     46     7.267857   1.939286   4.607143
258  Uiseong     47     4.778571   1.114286   4.642857
259  Uiseong     48     3.989286   0.203571   4.071429
260  Uiseong     49     1.768750   1.000000   5.281250
261  Uiseong     50    -0.570588   0.505882   5.882353
262  Uiseong     51    -0.146875   0.143750   5.812500
263  Uiseong     52     0.290625   0.837500   3.781250
264  Uiseong     53    -1.518750   1.375000   6.000000

In [27]:
average = average[average['weeks'] == weeks]
average.sort_values(by=['region'], axis=0,inplace=True)
average.reset_index(drop=True, inplace=True)
del average['weeks']
average = average[['region','temperature','rainfall', 'daylight']]
average

/Users/kimsejin/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    region  temperature  rainfall  daylight
0   Andong    21.302857  1.534286  9.600000
1  Gochang    20.434286  1.205714  7.057143
2  Goheung    20.222857  4.342857  7.714286
3    Sinan    18.122857  3.148571  6.971429
4  Uiseong    20.957143  1.302857  8.828571

In [28]:
data

    region  temperature  rainfall  daylight
0   Andong         22.5       0.0      12.0
1  Gochang         22.2       0.0       8.0
2  Goheung         20.7       0.0      12.0
3    Sinan         18.6       0.0      11.0
4  Uiseong         22.2       0.0      11.0

In [44]:
temperature = abs(data['temperature'] - average['temperature'])
temperature

0    1.197143
1    1.765714
2    0.477143
3    0.477143
4    1.242857
Name: temperature, dtype: float64

In [52]:
for i in temperature.index:
    if temperature[i] <= 1.5:
        temperature[i] = 0
    elif 1.5 < temperature[i] <= 3.0:
        temperature[i] = 1
    else:
        temperature[i] = 2
temperature

0    0.0
1    1.0
2    0.0
3    0.0
4    0.0
Name: temperature, dtype: float64

In [39]:
rainfall = abs(data['rainfall'] - average['rainfall'])
rainfall

0    1.534286
1    1.205714
2    4.342857
3    3.148571
4    1.302857
Name: rainfall, dtype: float64

In [53]:
for i in rainfall.index:
    if rainfall[i] <= 3.0:
        rainfall[i] = 0
    elif 3.0 < rainfall[i] <= 6.0:
        rainfall[i] = 1
    else:
        rainfall[i] = 2
rainfall

0    0.0
1    0.0
2    1.0
3    1.0
4    0.0
Name: rainfall, dtype: float64

In [40]:
daylight = abs(data['daylight'] - average['daylight'])
daylight

0    2.400000
1    0.942857
2    4.285714
3    4.028571
4    2.171429
Name: daylight, dtype: float64

In [54]:
for i in daylight.index:
    if daylight[i] <= 1.5:
        daylight[i] = 0
    elif 1.5 < daylight[i] <= 3.0:
        daylight[i] = 1
    else:
        daylight[i] = 2
daylight

0    1.0
1    0.0
2    2.0
3    2.0
4    1.0
Name: daylight, dtype: float64

In [55]:
array = {'temperature': temperature,
        'rainfall': rainfall,
        'daylight': daylight}

danger = pd.DataFrame(array)
danger

   temperature  rainfall  daylight
0          0.0       0.0       1.0
1          1.0       0.0       0.0
2          0.0       1.0       2.0
3          0.0       1.0       2.0
4          0.0       0.0       1.0

In [56]:
danger.to_json()

'{"temperature":{"0":0.0,"1":1.0,"2":0.0,"3":0.0,"4":0.0},"rainfall":{"0":0.0,"1":0.0,"2":1.0,"3":1.0,"4":0.0},"daylight":{"0":1.0,"1":0.0,"2":2.0,"3":2.0,"4":1.0}}'