In [1]:
import pandas as pd
a = pd.read_csv('./채소생산량_근채류__20200506160919.csv', encoding='euc-kr')
b = pd.read_csv('./채소생산량_엽채류__20200506150012.csv', encoding='euc-kr')
c = pd.read_csv('./채소생산량_조미채소__20200506145121.csv', encoding='euc-kr')

In [2]:
df = pd.concat([a,b,c],axis=1).T
df = df.rename(columns=df.iloc[0])
# df.drop(df.index[0], inplace=True)
df = df[df['시도별'] != '10a당 생산량 (kg)']
df['시도별'] = df['시도별'].str.replace(pat=':면적 (ha)', repl='', regex=False)
df['시도별'] = df['시도별'].str.replace(pat='생산량 (톤)', repl='Ton', regex=False)
df = df.reset_index(drop=True)
s = sorted(set(df['시도별']))[1:]

# 종류
print(s)


# 날씨
w = pd.read_csv('./weather_0020.csv')

w['지역(시)'] = w['지역(시)'].str.replace(pat='서울', repl='서울특별시',regex=False)
w['지역(시)'] = w['지역(시)'].str.replace(pat='광주', repl='광주광역시',regex=False)
w['지역(시)'] = w['지역(시)'].str.replace(pat='부산', repl='부산광역시',regex=False)
w['지역(시)'] = w['지역(시)'].str.replace(pat='대구', repl='대구광역시',regex=False)
w['지역(시)'] = w['지역(시)'].str.replace(pat='인천', repl='인천광역시',regex=False)
w['지역(시)'] = w['지역(시)'].str.replace(pat='대전', repl='대전광역시',regex=False)
w['지역(시)'] = w['지역(시)'].str.replace(pat='울산', repl='울산광역시',regex=False)
w['지역(시)'] = w['지역(시)'].str.replace(pat='제주특별자치도', repl='제주도',regex=False)


# 연도별로 쪼개기
years = ['2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012','2013','2014','2015','2016', '2017','2018','2019']

weather_list = []
prod_list = []
for i in years:
    prod_list.append(df[df['연도별']==i].reset_index(drop=True))
    weather_list.append(w[w['year']==int(i)].reset_index(drop=True))
    
prod_list[1]

['가을일반무', '가을총각무', '건고추', '고랭지무', '고랭지배추', '고추', '노지가을무', '노지가을배추', '노지겨울무', '노지겨울배추', '노지무', '노지배추', '노지봄무', '노지봄배추', '마늘', '무', '배추', '시도별', '시설무', '시설배추', '양파', '일반봄무', '일반봄배추', '풋고추']

,연도별,시도별,계,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주도
0,2001,무,38751,80,383,318,737,757,211,217,-,6495,5151,2576,4095,5884,5094,3325,2263,1165
1,2001,Ton,1731869,1727,18730,12427,36177,47958,9824,11405,-,259708,155438,98929,180729,318833,278561,130037,103005,68381
2,2001,노지무,32548,23,194,168,509,542,60,139,-,4458,5071,2414,3495,5231,4103,3090,1898,1153
3,2001,Ton,1501551,1039,10225,7499,23318,39304,2973,7193,-,193668,152268,93210,149727,307386,238673,121516,85598,67954
4,2001,노지봄무,18859,14,153,108,182,102,22,42,-,2436,4554,2021,1525,2123,1768,2249,1206,354
5,2001,Ton,620025,490,7765,4093,7993,4636,795,1344,-,82946,124931,76166,48602,73666,71445,71684,35656,7813
6,2001,일반봄무,15988,14,167,113,185,112,22,43,-,2454,1700,2010,1526,1933,2308,1865,1059,477
7,2001,Ton,506904,490,7765,4093,7993,4636,795,1344,-,82946,50898,75777,48602,54706,71445,59948,27653,7813
8,2001,고랭지무,4017,0,0,0,0,0,0,0,-,0,2854,11,0,551,0,389,212,0
9,2001,Ton,113121,0,0,0,0,0,0,0,-,0,74033,389,0,18960,0,11736,8003,0
10,2001,노지가을무,13689,9,41,60,327,440,38,97,-,2022,517,393,1970,3108,2335,841,692,799
11,2001,Ton,881526,549,2460,3406,15325,34668,2178,5849,-,110722,27337,17044,101125,233720,167228,49832,49942,60141
12,2001,가을일반무,12617,9,41,58,308,440,35,97,-,1639,453,328,1767,2875,2247,832,689,799
13,2001,Ton,843480,549,2460,3344,14605,34668,2034,5849,-,100094,25459,15938,93616,221289,164031,49554,49849,60141
14,2001,가을총각무,1072,0,0,2,19,0,3,0,-,383,64,65,203,233,88,9,3,0
15,2001,Ton,38046,0,0,62,720,0,144,0,-,10628,1878,1106,7509,12431,3197,278,93,0
16,2001,시설무,6203,57,189,150,228,215,151,78,-,2037,80,162,600,653,991,235,365,12
17,2001,Ton,230318,688,8505,4928,12859,8654,6851,4212,-,66040,3170,5719,31002,11447,39888,8521,17407,427
18,2001,배추,49539,98,895,585,382,440,141,176,-,5102,10220,3624,4152,4379,11037,4827,2887,594
19,2001,Ton,3040648,4322,77346,32676,29311,33763,10613,15990,-,355381,439152,220695,362686,291631,673575,257721,199653,36133
20,2001,노지배추,44419,30,733,371,242,313,104,159,-,3280,10081,3444,3648,3987,10517,4456,2468,586
21,2001,Ton,2804497,2663,66881,24936,20004,25508,8565,14989,-,277837,434475,215664,338948,273485,649395,241642,173763,35742
22,2001,노지봄배추,30250,8,452,232,66,132,26,49,-,1081,9260,2326,796,2552,8560,3104,1253,353
23,2001,Ton,1357357,353,26035,10486,2411,6970,1147,1715,-,46656,373976,120366,25798,104040,449742,131413,42397,13852
24,2001,일반봄배추,20016,8,452,232,66,132,26,49,-,1081,1983,2285,796,708,8560,2732,553,353
25,2001,Ton,958206,353,26035,10486,2411,6970,1147,1715,-,46656,83405,118729,25798,34650,449742,116001,20256,13852
26,2001,고랭지배추,10234,0,0,0,0,0,0,0,-,0,7277,41,0,1844,0,372,700,0
27,2001,Ton,399151,0,0,0,0,0,0,0,-,0,290571,1637,0,69390,0,15412,22141,0
28,2001,노지가을배추,14169,22,281,139,176,181,78,110,-,2199,821,1118,2852,1435,1957,1352,1215,233
29,2001,Ton,1447140,2310,40846,14450,17593,18538,7418,13274,-,231181,60499,95298,313150,169445,199653,110229,131366,21890
30,2001,시설배추,5120,68,162,214,140,127,37,17,-,1822,139,180,504,392,520,371,419,8
31,2001,Ton,236151,1659,10465,7740,9307,8255,2048,1001,-,77544,4677,5031,23738,18146,24180,16079,25890,391
32,2001,고추,76253,34,114,224,856,717,199,232,-,6011,5230,11211,8250,9121,10716,18527,4783,28
33,2001,Ton,411750,165,1081,2009,3405,25099,1058,810,-,14568,18693,35300,34166,29268,65807,56108,123945,268
34,2001,건고추,70736,30,77,188,822,181,178,223,-,5740,5019,11027,7793,8858,9567,18124,2893,16
35,2001,Ton,180120,47,163,366,1918,443,377,468,-,8907,11652,29951,20072,24237,27660,47512,6330,17
36,2001,풋고추,5517,4,37,36,34,536,21,9,-,271,211,184,457,263,1149,403,1890,12
37,2001,Ton,231630,118,918,1643,1487,24656,681,342,-,5661,7041,5349,14094,5031,38147,8596,117615,251
38,2001,양파,18995,0,6,102,11,4,1,20,-,45,218,30,264,502,9353,3401,3811,1227
39,2001,Ton,1073708,0,363,5465,222,222,44,907,-,1323,10969,1566,11484,24242,518530,191272,230375,76724
40,2001,마늘,37118,1,25,329,162,48,21,36,-,909,564,863,3315,739,15869,4578,6095,3564
41,2001,Ton,406385,7,202,3747,946,474,120,289,-,6027,4078,4910,30615,7639,179310,46949,70713,50359

In [3]:
weather_list[1]

,year,month,지역(시),평균기온,최고기온,최저기온,강수량,일조시간,일사량,습도,운량,적설량,순간최대풍속
0,2001,1,강원도,-5.779677e+00,-0.526452,-10.912258,1.468710,4.858065,2.512903,62.535484,0.0,0.0,0.0
1,2001,1,경기도,-4.774194e+00,0.412903,-9.764516,1.261290,4.537634,2.838710,61.225806,0.0,0.0,0.0
2,2001,1,경상남도,1.505376e-02,5.039068,-4.442652,2.000358,5.107527,0.996416,57.053763,0.0,0.0,0.0
3,2001,1,경상북도,-2.163930e+00,2.612317,-6.509091,1.321701,4.841642,1.363636,58.835777,0.0,0.0,0.0
4,2001,1,광주광역시,1.032258e-01,4.825806,-3.748387,1.625806,4.290323,9.225806,61.161290,0.0,0.0,0.0
5,2001,1,대구광역시,6.741935e-01,4.748387,-2.870968,1.003226,5.451613,8.419355,55.064516,0.0,0.0,0.0
6,2001,1,대전광역시,-2.245161e+00,2.390323,-6.616129,1.974194,4.612903,8.806452,68.000000,0.0,0.0,0.0
7,2001,1,부산광역시,2.651613e+00,6.754839,-0.677419,1.948387,4.741935,8.225806,53.516129,0.0,0.0,0.0
8,2001,1,서울특별시,-4.158065e+00,-0.767742,-7.777419,1.270968,3.161290,6.612903,62.096774,0.0,0.0,0.0
9,2001,1,울산광역시,1.558065e+00,5.580645,-1.903226,1.916129,5.516129,0.000000,48.516129,0.0,0.0,0.0
10,2001,1,인천광역시,-5.017742e+00,-0.566129,-9.398387,1.377419,5.435484,4.112903,66.048387,0.0,0.0,0.0
11,2001,1,전라남도,1.164919e+00,5.278226,-2.733468,1.421774,4.479839,1.967742,62.818548,0.0,0.0,0.0
12,2001,1,전라북도,-1.764055e+00,3.244700,-6.429032,2.329954,4.529954,1.087558,70.769585,0.0,0.0,0.0
13,2001,1,제주도,5.810484e+00,9.068548,2.688710,4.152419,3.217742,3.217742,67.185484,0.0,0.0,0.0
14,2001,1,충청남도,-2.970323e+00,2.049032,-7.951613,2.012258,4.425806,1.735484,69.393548,0.0,0.0,0.0
15,2001,1,충청북도,-4.232258e+00,0.818548,-9.198387,1.616129,4.637097,4.250000,63.427419,0.0,0.0,0.0
16,2001,2,강원도,-1.899286e+00,3.772857,-7.213571,1.768929,5.557143,3.325000,64.078571,0.0,0.0,0.0
17,2001,2,경기도,-1.184524e+00,4.145238,-6.077381,1.771429,5.250000,3.630952,61.678571,0.0,0.0,0.0
18,2001,2,경상남도,2.902381e+00,8.920635,-2.303175,2.683730,5.996032,1.277778,53.138889,0.0,0.0,0.0
19,2001,2,경상북도,1.001623e+00,6.553896,-4.013961,2.136688,5.892857,1.818182,58.594156,0.0,0.0,0.0
20,2001,2,광주광역시,2.442857e+00,8.157143,-2.328571,2.996429,5.035714,12.321429,55.821429,0.0,0.0,0.0
21,2001,2,대구광역시,4.150000e+00,8.896429,-0.396429,2.210714,6.392857,11.357143,51.142857,0.0,0.0,0.0
22,2001,2,대전광역시,9.321429e-01,6.325000,-3.492857,2.500000,5.642857,11.464286,63.821429,0.0,0.0,0.0
23,2001,2,부산광역시,5.725000e+00,10.296429,2.042857,1.903571,4.857143,10.142857,48.785714,0.0,0.0,0.0
24,2001,2,서울특별시,-2.892857e-01,3.714286,-3.728571,1.632143,4.107143,9.142857,60.071429,0.0,0.0,0.0
25,2001,2,울산광역시,4.339286e+00,9.221429,-0.042857,2.007143,6.214286,0.000000,46.678571,0.0,0.0,0.0
26,2001,2,인천광역시,-1.342857e+00,3.053571,-5.396429,1.339286,6.535714,5.428571,67.035714,0.0,0.0,0.0
27,2001,2,전라남도,2.863393e+00,8.327679,-1.588839,2.804911,5.531250,2.785714,60.651786,0.0,0.0,0.0
28,2001,2,전라북도,7.698980e-01,6.643367,-4.121939,2.930102,5.663265,1.561224,66.122449,0.0,0.0,0.0
29,2001,2,제주도,6.752679e+00,10.513393,3.372321,2.855357,4.276786,4.750000,64.580357,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,2001,11,경상남도,8.035926e+00,15.235556,2.402222,0.370741,6.577778,1.203704,57.937037,0.0,0.0,0.0
163,2001,11,경상북도,6.314848e+00,13.255152,0.813636,0.728182,6.684848,1.827273,59.939394,0.0,0.0,0.0
164,2001,11,광주광역시,8.033333e+00,14.213333,3.036667,0.510000,5.500000,11.066667,62.333333,0.0,0.0,0.0
165,2001,11,대구광역시,8.300000e+00,14.133333,3.473333,0.266667,7.466667,10.300000,53.000000,0.0,0.0,0.0
166,2001,11,대전광역시,6.370000e+00,12.666667,1.000000,0.360000,5.900000,9.733333,66.866667,0.0,0.0,0.0
167,2001,11,부산광역시,1.140667e+01,17.110000,7.473333,0.430000,5.933333,11.133333,51.666667,0.0,0.0,0.0
168,2001,11,서울특별시,7.046667e+00,11.506667,2.910000,0.433333,3.966667,7.833333,58.366667,0.0,0.0,0.0
169,2001,11,울산광역시,9.940000e+00,15.780000,5.040000,0.440000,7.066667,0.000000,50.833333,0.0,0.0,0.0
170,2001,11,인천광역시,6.730000e+00,11.835000,2.176667,0.491667,6.516667,4.466667,61.800000,0.0,0.0,0.0
171,2001,11,전라남도,8.550000e+00,14.502500,3.725417,0.650000,6.987500,2.675000,62.575000,0.0,0.0,0.0
172,2001,11,전라북도,6.451905e+00,13.120000,1.030952,0.625238,6.347619,1.323810,69.309524,0.0,0.0,0.0
173,2001,11,제주도,1.220083e+01,15.822500,8.972500,1.837500,6.166667,4.941667,58.575000,0.0,0.0,0.0
174,2001,11,충청남도,5.955333e+00,13.026000,0.111333,0.333333,7.360000,2.020000,70.113333,0.0,0.0,0.0
175,2001,11,충청북도,4.678333e+00,11.974167,-1.299167,0.246667,7.016667,4.991667,63.558333,0.0,0.0,0.0
176,2001,12,강원도,-2.524516e+00,3.519355,-7.778387,0.590000,6.345161,2.480645,55.003226,0.0,0.0,0.0
177,2001,12,경기도,-1.893548e+00,4.023656,-7.316129,0.389247,6.537634,2.752688,58.774194,0.0,0.0,0.0
178,2001,12,경상남도,2.589606e+00,8.278136,-2.092115,1.203584,5.788530,1.032258,52.770609,0.0,0.0,0.0
179,2001,12,경상북도,2.434018e-01,5.796188,-4.428152,0.878299,5.953079,1.627566,54.563050,0.0,0.0,0.0
180,2001,12,광주광역시,2.454839e+00,7.051613,-1.051613,1.725806,4.096774,8.677419,61.838710,0.0,0.0,0.0
181,2001,12,대구광역시,1.877419e+00,6.629032,-1.919355,0.729032,7.032258,9.000000,48.838710,0.0,0.0,0.0
182,2001,12,대전광역시,1.146037e-16,5.012903,-4.512903,0.658065,5.709677,8.612903,64.548387,0.0,0.0,0.0
183,2001,12,부산광역시,4.754839e+00,9.880645,1.245161,0.925806,5.032258,9.354839,44.677419,0.0,0.0,0.0
184,2001,12,서울특별시,-5.935484e-01,3.438710,-3.977419,0.506452,4.064516,7.645161,49.258065,0.0,0.0,0.0
185,2001,12,울산광역시,4.106452e+00,8.725806,0.377419,1.351613,6.580645,0.000000,41.419355,0.0,0.0,0.0
186,2001,12,인천광역시,-9.596774e-01,3.537097,-5.001613,0.751613,6.564516,4.080645,53.951613,0.0,0.0,0.0
187,2001,12,전라남도,3.402016e+00,7.574597,-0.335887,1.418145,5.221774,1.778226,60.455645,0.0,0.0,0.0
188,2001,12,전라북도,6.705069e-01,5.627650,-3.497696,1.473272,5.207373,1.018433,70.138249,0.0,0.0,0.0
189,2001,12,제주도,7.114516e+00,9.937903,4.482258,3.662097,2.798387,2.451613,62.653226,0.0,0.0,0.0
190,2001,12,충청남도,-4.406452e-01,5.192903,-5.348387,0.720000,6.664516,1.767742,68.800000,0.0,0.0,0.0
191,2001,12,충청북도,-1.916935e+00,4.108871,-7.219355,0.627419,6.443548,4.435484,61.233871,0.0,0.0,0.0

In [4]:
weather_location = []
location = ['강원도','경기도','경상남도','경상북도','광주광역시','대구광역시','대전광역시','부산광역시','울산광역시','인천광역시','전라남도','전라북도','서울특별시', '제주도', '충청남도','충청북도']

for i in weather_list:
    for j in location:
        weather_location.append(i[i['지역(시)']==j].reset_index(drop=True))

prod_location = []
for i in prod_list:
    for j in location:
        prod_location.append(i[['연도별', '시도별',j]].reset_index(drop=True))

print(len(weather_location), len(prod_location))
n = 133
prod_location[n], weather_location[n]

320 320

(     연도별     시도별  대구광역시
 0   2008       무    162
 1   2008     Ton   8413
 2   2008     노지무     83
 3   2008     Ton   4401
 4   2008    노지봄무     41
 5   2008     Ton   1506
 6   2008    일반봄무     41
 7   2008     Ton   1506
 8   2008    고랭지무      0
 9   2008     Ton      0
 10  2008   노지가을무     42
 11  2008     Ton   2895
 12  2008   가을일반무     42
 13  2008     Ton   2895
 14  2008   가을총각무      0
 15  2008     Ton      0
 16  2008     시설무     79
 17  2008     Ton   4012
 18  2008      배추    352
 19  2008     Ton  20169
 20  2008    노지배추    178
 21  2008     Ton  13019
 22  2008   노지봄배추     66
 23  2008     Ton   3211
 24  2008   일반봄배추     66
 25  2008     Ton   3211
 26  2008   고랭지배추      0
 27  2008     Ton      0
 28  2008  노지가을배추    112
 29  2008     Ton   9808
 30  2008    시설배추    174
 31  2008     Ton   7150
 32  2008      고추    215
 33  2008     Ton   2862
 34  2008     건고추    158
 35  2008     Ton    338
 36  2008     풋고추     57
 37  2008     Ton   2524
 38  2008      양파     99
 39  2008     Ton   6714
 40  2008      마늘    248
 41  2008     Ton   3907,
     year  month  지역(시)       평균기온       최고기온       최저기온       강수량      일조시간  \
 0   2008      1  대구광역시   1.522581   5.622581  -1.970968  1.232258  4.935484
 1   2008      2  대구광역시   1.537931   6.965517  -3.168966  0.172414  8.000000
 2   2008      3  대구광역시   8.867742  14.809677   3.858065  0.761290  6.161290
 3   2008      4  대구광역시  14.803333  20.960000   9.286667  1.716667  7.033333
 4   2008      5  대구광역시  19.729032  25.712903  14.151613  2.654839  7.322581
 5   2008      6  대구광역시  21.143333  25.803333  17.176667  6.243333  4.233333
 6   2008      7  대구광역시  28.425806  33.058065  24.793548  2.506452  4.483871
 7   2008      8  대구광역시  25.819355  30.735484  22.196774  7.590323  5.967742
 8   2008      9  대구광역시  23.043333  28.026667  18.946667  0.730000  5.233333
 9   2008     10  대구광역시  17.761290  23.551613  12.629032  0.387097  7.161290
 10  2008     11  대구광역시   9.503333  14.666667   4.926667  0.390000  5.366667
 11  2008     12  대구광역시   3.283871   8.696774  -1.258065  0.370968  5.612903

           일사량         습도        운량  적설량    순간최대풍속
 0    7.225806  55.258065  4.193548  0.0  7.258065
 1   13.758621  37.620690  2.344828  0.0  9.296552
 2   14.419355  50.161290  3.677419  0.0  8.141935
 3   18.166667  53.166667  4.433333  0.0  8.683333
 4   20.387097  53.193548  4.580645  0.0  8.335484
 5   16.566667  68.900000  7.400000  0.0  8.326667
 6   16.935484  68.741935  7.161290  0.0  7.361290
 7   17.387097  68.967742  6.161290  0.0  8.432258
 8   14.566667  66.066667  5.633333  0.0  7.046667
 9   13.096774  58.064516  3.903226  0.0  6.822581
 10   9.300000  55.933333  4.166667  0.0  7.263333
 11   8.322581  49.645161  2.806452  0.0  7.296774  )

In [5]:
for i in range(len(prod_location)):
    local = set(weather_location[i]['지역(시)'])
#     prod_location[i]
    idx = prod_location[i][::2].index.values
    col_name = []
    col_values = []
    for k in idx:
        col_name.append(prod_location[i].iloc[k]['시도별'])
        col_values.append(prod_location[i].iloc[k+1][local][0])
    for j in range(len(col_name)):
#         print(col_name[j], col_values[j])
        weather_location[i][col_name[j]] = col_values[j]

In [6]:
weather_location[1]

,year,month,지역(시),평균기온,최고기온,최저기온,강수량,일조시간,일사량,습도,...,노지봄배추,일반봄배추,고랭지배추,노지가을배추,시설배추,고추,건고추,풋고추,양파,마늘
0,2000,1,경기도,-2.425806,2.120430,-6.701075,1.743011,4.956989,2.182796,65.440860,...,51949,51949,0,215763,97020,21177,14347,6830,1010,6389
1,2000,2,경기도,-2.229885,3.152874,-7.698851,0.057471,6.574713,3.632184,55.114943,...,51949,51949,0,215763,97020,21177,14347,6830,1010,6389
2,2000,3,경기도,5.374194,12.084946,-1.009677,0.076344,6.548387,4.913978,51.247312,...,51949,51949,0,215763,97020,21177,14347,6830,1010,6389
3,2000,4,경기도,11.080000,17.907778,4.334444,0.745556,6.688889,5.900000,49.733333,...,51949,51949,0,215763,97020,21177,14347,6830,1010,6389
4,2000,5,경기도,17.211828,23.544086,11.665591,1.996774,5.849462,6.075269,64.494624,...,51949,51949,0,215763,97020,21177,14347,6830,1010,6389
5,2000,6,경기도,22.813333,28.831111,17.813333,4.146667,5.722222,6.155556,66.933333,...,51949,51949,0,215763,97020,21177,14347,6830,1010,6389
6,2000,7,경기도,26.072043,31.115054,22.067742,8.997849,5.043011,5.838710,72.892473,...,51949,51949,0,215763,97020,21177,14347,6830,1010,6389
7,2000,8,경기도,25.262366,30.011828,21.833333,12.804301,1.645161,4.860215,78.075269,...,51949,51949,0,215763,97020,21177,14347,6830,1010,6389
8,2000,9,경기도,19.221111,24.481111,15.227778,5.924444,1.688889,4.388889,74.811111,...,51949,51949,0,215763,97020,21177,14347,6830,1010,6389
9,2000,10,경기도,13.081720,19.544086,7.756989,0.522581,3.043011,3.881720,71.000000,...,51949,51949,0,215763,97020,21177,14347,6830,1010,6389
10,2000,11,경기도,5.191111,11.517778,-0.108889,0.900000,4.955556,2.888889,64.944444,...,51949,51949,0,215763,97020,21177,14347,6830,1010,6389
11,2000,12,경기도,-0.281720,5.177419,-5.483871,0.674194,4.956989,2.655914,59.763441,...,51949,51949,0,215763,97020,21177,14347,6830,1010,6389

In [7]:
dropna = weather_location[1].T[weather_location[1].T[0] != 0]
dropna = dropna[dropna[0] != '0']
dropna = dropna[dropna[0] != '-']

dropna

,0,1,2,3,4,5,6,7,8,9,10,11
year,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000
month,1,2,3,4,5,6,7,8,9,10,11,12
지역(시),경기도,경기도,경기도,경기도,경기도,경기도,경기도,경기도,경기도,경기도,경기도,경기도
평균기온,-2.42581,-2.22989,5.37419,11.08,17.2118,22.8133,26.072,25.2624,19.2211,13.0817,5.19111,-0.28172
최고기온,2.12043,3.15287,12.0849,17.9078,23.5441,28.8311,31.1151,30.0118,24.4811,19.5441,11.5178,5.17742
최저기온,-6.70108,-7.69885,-1.00968,4.33444,11.6656,17.8133,22.0677,21.8333,15.2278,7.75699,-0.108889,-5.48387
강수량,1.74301,0.0574713,0.0763441,0.745556,1.99677,4.14667,8.99785,12.8043,5.92444,0.522581,0.9,0.674194
일조시간,4.95699,6.57471,6.54839,6.68889,5.84946,5.72222,5.04301,1.64516,1.68889,3.04301,4.95556,4.95699
일사량,2.1828,3.63218,4.91398,5.9,6.07527,6.15556,5.83871,4.86022,4.38889,3.88172,2.88889,2.65591
습도,65.4409,55.1149,51.2473,49.7333,64.4946,66.9333,72.8925,78.0753,74.8111,71,64.9444,59.7634
무,268739,268739,268739,268739,268739,268739,268739,268739,268739,268739,268739,268739
노지무,188665,188665,188665,188665,188665,188665,188665,188665,188665,188665,188665,188665
노지봄무,83141,83141,83141,83141,83141,83141,83141,83141,83141,83141,83141,83141
일반봄무,83141,83141,83141,83141,83141,83141,83141,83141,83141,83141,83141,83141
노지가을무,105524,105524,105524,105524,105524,105524,105524,105524,105524,105524,105524,105524
시설무,80074,80074,80074,80074,80074,80074,80074,80074,80074,80074,80074,80074
배추,364732,364732,364732,364732,364732,364732,364732,364732,364732,364732,364732,364732
노지배추,267712,267712,267712,267712,267712,267712,267712,267712,267712,267712,267712,267712
노지봄배추,51949,51949,51949,51949,51949,51949,51949,51949,51949,51949,51949,51949
일반봄배추,51949,51949,51949,51949,51949,51949,51949,51949,51949,51949,51949,51949
노지가을배추,215763,215763,215763,215763,215763,215763,215763,215763,215763,215763,215763,215763
시설배추,97020,97020,97020,97020,97020,97020,97020,97020,97020,97020,97020,97020
고추,21177,21177,21177,21177,21177,21177,21177,21177,21177,21177,21177,21177
건고추,14347,14347,14347,14347,14347,14347,14347,14347,14347,14347,14347,14347
풋고추,6830,6830,6830,6830,6830,6830,6830,6830,6830,6830,6830,6830
양파,1010,1010,1010,1010,1010,1010,1010,1010,1010,1010,1010,1010
마늘,6389,6389,6389,6389,6389,6389,6389,6389,6389,6389,6389,6389

In [8]:
dropna.corr()

Empty DataFrame
Columns: []
Index: []