In [1]:
import pandas as pd
year_list = []
month_list = []
year = 2000
for i in range(20):
    for j in range(1,13):
        year_list.append(year)
        month_list.append(j)
    year += 1

In [2]:
price = pd.DataFrame(data={'년도': year_list, '월':month_list, '가격':[6192,8154,8522,7832,4058,2901,4466,4534,5997,4995,2680,2162,2552,2822,3540,3890,2638,6023,6633,7108,6098,3797,2323,3046,3125,2614,2284,2153,3098,3300,3611,6888,8710,4942,4062,6918,7161,7333,10429,9860,6524,3608,5182,6529,8361,8474,5988,3871,2964,2709,3542,4162,3270,3400,6549,12057,8607,3951,2776,2485,2398,2887,3187,3579,3090,2961,4792,5883,9085,9937,6755,7106,6105,6778,8398,7942,5986,3340,4035,9534,10704,3839,3020,3495,2781,2287,2679,3102,2705,3991,5813,6057,9648,9480,7914,6309,4740,4667,4691,5193,3951,3461,3430,6183,5204,3732,3970,3810,3911,3960,6236,11552,9942,4270,4870,6848,6855,4357,3527,3647,4913,7979,11327,13859,9453,6186,8965,9291,19516,15726,9216,11174,13310,12259,13105,8176,3794,3352,6729,10895,8995,5865,3645,3219,3500,5245,9210,12140,7262,4918,7945,9018,12790,9952,7900,10816,12182,12358,12400,11243,6938,5289,6287,13424,12511,5636,5586,5024,4623,4074,3604,3564,3369,3907,6010,7684,8042,4970,4172,3838,3800,4153,4850,4991,8978,7468,6448,6670,6110,4424,4445,4333,5520,8228,12005,15079,11430,6248,7505,15236,21042,10630,8473,9305,10110,10065,9468,7775,4297,4895,8459,15211,17419,7251,6074,6497,6828,9109,8733,8176,6406,5728,10402,18682,15165,8468,7468,6168
,4848,4020,3735,3414,3904,5746,7365,8771,14847,15600,9671,9890]})
path = '무_공급량/무'
o00 = pd.read_excel('./{}_00.xlsx'.format(path))
o01 = pd.read_excel('./{}_01.xlsx'.format(path))
o02 = pd.read_excel('./{}_02.xlsx'.format(path))
o03 = pd.read_excel('./{}_03.xlsx'.format(path))
o04 = pd.read_excel('./{}_04.xlsx'.format(path))
o05 = pd.read_excel('./{}_05.xlsx'.format(path))
o06 = pd.read_excel('./{}_06.xlsx'.format(path))
o07 = pd.read_excel('./{}_07.xlsx'.format(path))
o08 = pd.read_excel('./{}_08.xlsx'.format(path))
o09 = pd.read_excel('./{}_09.xlsx'.format(path))
o10 = pd.read_excel('./{}_10.xlsx'.format(path))
o11 = pd.read_excel('./{}_11.xlsx'.format(path))
o12 = pd.read_excel('./{}_12.xlsx'.format(path))
o13 = pd.read_excel('./{}_13.xlsx'.format(path))
o14 = pd.read_excel('./{}_14.xlsx'.format(path))
o15 = pd.read_excel('./{}_15.xlsx'.format(path))
o16 = pd.read_excel('./{}_16.xlsx'.format(path))
o17 = pd.read_excel('./{}_17.xlsx'.format(path))
o18 = pd.read_excel('./{}_18.xlsx'.format(path))
o19 = pd.read_excel('./{}_19.xlsx'.format(path))


product = pd.concat([o00, o01, o02, o03, o04, o05, o06, o07, o08, o09, o10, o11, o12, o13, o14, o15, o16, o17, o18, o19])
product['year'] = product['거래년월일'].apply(lambda x: str(x)[:4]).astype(str)
product['month'] = product['거래년월일'].apply(lambda x: str(x)[4:6]).astype(str)
product['거래량'] = product['거래량'].apply(lambda x: ''.join(str(x).split(','))).astype(int) 
df = product[['year', 'month','거래량']]
total = df.groupby(['year','month'], as_index=False).sum()
total = total[:-2]
cat = pd.concat([price, total], axis=1)
result = cat[['year','month','거래량','가격']]

result.groupby('year').corr()

               거래량        가격
year
2000 거래량  1.000000 -0.198743
     가격  -0.198743  1.000000
2001 거래량  1.000000  0.071768
     가격   0.071768  1.000000
2002 거래량  1.000000  0.168580
     가격   0.168580  1.000000
2003 거래량  1.000000  0.187175
     가격   0.187175  1.000000
2004 거래량  1.000000 -0.473919
     가격  -0.473919  1.000000
2005 거래량  1.000000 -0.456869
     가격  -0.456869  1.000000
2006 거래량  1.000000  0.293030
     가격   0.293030  1.000000
2007 거래량  1.000000  0.793532
     가격   0.793532  1.000000
2008 거래량  1.000000  0.235134
     가격   0.235134  1.000000
2009 거래량  1.000000  0.521282
     가격   0.521282  1.000000
2010 거래량  1.000000  0.055176
     가격   0.055176  1.000000
2011 거래량  1.000000  0.583150
     가격   0.583150  1.000000
2012 거래량  1.000000  0.440110
     가격   0.440110  1.000000
2013 거래량  1.000000  0.689764
     가격   0.689764  1.000000
2014 거래량  1.000000  0.026343
     가격   0.026343  1.000000
2015 거래량  1.000000 -0.403514
     가격  -0.403514  1.000000
2016 거래량  1.000000  0.427793
     가격   0.427793  1.000000
2017 거래량  1.000000  0.386194
     가격   0.386194  1.000000
2018 거래량  1.000000  0.009157
     가격   0.009157  1.000000
2019 거래량  1.000000 -0.246817
     가격  -0.246817  1.000000

In [ ]:
price = pd.DataFrame(data={'년도': year_list, '월':month_list, '가격':[10318,11296,9612,9163,6271,4462,5204,6141,8240,8045,4826,4229,4043,3935,4000,3388,4705,6752,12251,11513,7264,4103,2911,3448,3365,3051,2864,3842,6650,6929,6624,7463,11805,8694,8050,10700,10184,9908,13403,13616,8292,4043,3834,3866,7666,10630,9855,7480,4517,4062,4502,4333,3237,5415,11356,24381,16905,7148,4263,3342,3366,3071,2511,4634,5173,4816,9135,10037,14582,14230,11936,10615,7947,8472,8705,7795,6297,6880,7133,11247,14485,7305,4316,3824,3173,3583,4419,5379,5429,11419,10794,9769,11501,15244,13710,11509,7545,5764,6242,5817,5434,4925,4840,6903,6086,5629,6015,5704,6188,6180,5935,6078,7492,5692,6423,7014,7033,6657,6295,5785,5734,6926,8596,12727,15305,14484,19164,20736,22737,28461,17418,15165,10265,10419,12536,11101,8337,5311,10924,24445,14590,7692,5295,5013,5421,7490,8297,7850,9205,10535,13118,9845,13012,16648,13168,13541,9545,8954,8650,8909,14185,13679,11017,13562,14311,8857,7833,7062,6650,6188,6657,7320,7806,7780,8245,8853,9589,8868,7380,7384,6805,7682,7755,7727,8367,11412,15461,10946,7135,6515,7341,7345,8510,10822,12100,15910,14465,9227,10276,13136,20168,22976,13830,20962,16500,14790,12755,12216,11937,8295,10686,17705,14324,7091,6618,7234,7088,13589,15114,16371,18990,9831,13700,22318,20682,10943,6512,5979,5968,6276,5545,6106,7285,7478,7115,6914,10563,17638,17481,21660]})
path = '배추_공급량/배추'
o00 = pd.read_excel('./{}_00.xlsx'.format(path))
o01 = pd.read_excel('./{}_01.xlsx'.format(path))
o02 = pd.read_excel('./{}_02.xlsx'.format(path))
o03 = pd.read_excel('./{}_03.xlsx'.format(path))
o04 = pd.read_excel('./{}_04.xlsx'.format(path))
o05 = pd.read_excel('./{}_05.xlsx'.format(path))
o06 = pd.read_excel('./{}_06.xlsx'.format(path))
o07 = pd.read_excel('./{}_07.xlsx'.format(path))
o08 = pd.read_excel('./{}_08.xlsx'.format(path))
o09 = pd.read_excel('./{}_09.xlsx'.format(path))
o10 = pd.read_excel('./{}_10.xlsx'.format(path))
o11 = pd.read_excel('./{}_11.xlsx'.format(path))
o12 = pd.read_excel('./{}_12.xlsx'.format(path))
o13 = pd.read_excel('./{}_13.xlsx'.format(path))
o14 = pd.read_excel('./{}_14.xlsx'.format(path))
o15 = pd.read_excel('./{}_15.xlsx'.format(path))
o16 = pd.read_excel('./{}_16.xlsx'.format(path))
o17 = pd.read_excel('./{}_17.xlsx'.format(path))
o18 = pd.read_excel('./{}_18.xlsx'.format(path))
o19 = pd.read_excel('./{}_19.xlsx'.format(path))


product = pd.concat([o00, o01, o02, o03, o04, o05, o06, o07, o08, o09, o10, o11, o12, o13, o14, o15, o16, o17, o18, o19])
product['year'] = product['거래년월일'].apply(lambda x: str(x)[:4]).astype(str)
product['month'] = product['거래년월일'].apply(lambda x: str(x)[4:6]).astype(str)
product['거래량'] = product['거래량'].apply(lambda x: ''.join(str(x).split(','))).astype(int) 
df = product[['year', 'month','거래량']]
total = df.groupby(['year','month'], as_index=False).sum()
total = total[:-2]
cat = pd.concat([price, total], axis=1)
result = cat[['year','month','거래량','가격']]

result.groupby('year').corr()